### ISSUE TITLE
[question] Built-in Docker Registry

### ISSUE THREAD

**Issue by whitlockjc** [TheNewNormal/corectl.app#27]
The project README suggests that the Docker Registry is now provided by this project.  If I run `corectl.app` and try to access `http://192.168.64.1:5000/v2/_catalog`, nothing responds.  It also shows no VMs running.  Is the Docker Registry only ran when you have other VMs running?  I'm trying to update my [gist for developing against/for Kubernetes](https://gist.github.com/whitlockjc/6caf2aaeb94891976390fe62426016c1) to use your DMGs instead of `brew` and I wanted to make sure I document this right.

**Comment by whitlockjc** [comment]
Yup, that was it.  Once I ran Kube-Solo.app and had it running, the registry was accessible.  Sorry for the noise.

**Comment by rimusz** [comment]
yup, it is just a go binary running by `corectl.app` so in that way it allows registry to be shareable between all VMs
