### ISSUE TITLE
Can't use sudo

### ISSUE THREAD

**Issue by davecaplinger** [TheNewNormal/corectl.app#28]
I'm not yet sure why, but corectl.app won't accept my sudo password.  Entering the password when prompted just re-displays the same dialog again, and generates these logs in system.log:

```
Jul 29 14:48:12 dcaplinger-mac sudo[3484]: dcaplinger : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=validate
Jul 29 14:48:12 dcaplinger-mac sudo[3486]: dcaplinger : a password is required ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/uptime
Jul 29 14:48:12 dcaplinger-mac corectl[3447]: corectld running status: 'no'
Jul 29 14:48:12 dcaplinger-mac corectl[3447]: sudo password is incorrect !!!

```

If I manually run `/Applications/corectl.app/Contents/Resources/validate_sudo_password.command` (and provide my password), it returns 'yes'. Likewise, manually running `.../check_saved_sudo_password.command` also returns 'yes'.

(FWIW, I'm running corectl.app 0.2.2 on OS X 10.11.6.)

**Comment by rimusz** [comment]
hmm, seen that problem only on Siera. you have two options:
in `check_saved_sudo_password.command` change echo "" to:
```
    then
        # sudo password is correct
        echo -n "yes"
    else
        # sudo password is not correct
        echo -n "no"
    fi
```

or you can set password with:
```
security add-generic-password -a corectl-app -s corectl-app -w $your_password -U
```

But try the first option, please, if that works I can update the App.
Thanks

**Comment by davecaplinger** [comment]
I changed the `echo "blah"` cases to `echo -n "blah"` (adding `-n`) as you described, and now it works!  Thank you!

**Comment by rimusz** [comment]
i will keep it open, need to fix the problem

**Comment by davecaplinger** [comment]
Looks like it was my sudoers config.  I could start the corectl.app and see the menu bar item, but it would fail to start corectld (and as you gathered, it also failed to copy the tools in into /usr/local/sbin).

Some logs I saw when trying to start corectl.app:

```
Aug  1 11:44:06 dcaplinger-mac corectl[25581]: applicationDirectory: '/Applications/corectl.app/Contents/Resources'
Aug  1 11:44:06 dcaplinger-mac corectl[25581]: DMG resource path: '/Volumes/corectl/corectl.app/Contents/Resources'
Aug  1 11:44:07 dcaplinger-mac corectl[25581]: Corectld update status: 'no'
Aug  1 11:44:17 dcaplinger-mac sudo[25635]: dcaplinger : no tty present and no askpass program specified ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/pkill -f corectld.runner
Aug  1 11:44:17 dcaplinger-mac sudo[25656]: dcaplinger : no tty present and no askpass program specified ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/nohup /usr/local/sbin/corectld start --user dcaplinger
Aug  1 11:44:19 dcaplinger-mac corectl[25581]: App update status: 'no'
Aug  1 11:44:21 dcaplinger-mac corectl[25581]: corectld running status: 'no'
```

Changing my sudoers file to include `NOPASSWD` for my account fixed my problem and now it starts correctly (and I can see corectld running).

**Comment by rimusz** [comment]
@davecaplinger I never like to mess with `sudoers` file, need to think a way to avoid such issues.

**Comment by davecaplinger** [comment]
If you can call `AuthorizationExecuteWithPrivileges` directly, you may be able to eliminate the need to store a keychain entry for the sudo password as well.  Alternatively, you can wrap your sudo calls with an AppleScript that does the privilege escalation (and password prompting) for you.  Sorry I can't be more help than this; both are described here:  http://stackoverflow.com/questions/10283062/getting-sudo-to-ask-for-password-via-the-gui

**Comment by rimusz** [comment]
the whole point of saving user's password to the keychain is, that user does not get asked for it on app's start, `corectld` server restart.
Invoking applescript for the `sudo`, makes more difficult to check such things in the app, which needs to wait till `sudo` business is done and etc.

**Comment by rimusz** [comment]
@davecaplinger please check the latest version v0.2.3, it does not save user password to keychain anymore, it asks for user password when `corectld start` runs.
It should eliminate your problem, so closing this one.

**Comment by davecaplinger** [comment]
v0.2.3 works great for me; thank you very much!

**Comment by rimusz** [comment]
awesome, thanks for letting us know that it works fine for you now

**Comment by harobed** [comment]
Same bug with 0.2.8 :(
