### ISSUE TITLE
corectld fails to start

### ISSUE THREAD

**Issue by rrva** [TheNewNormal/corectl.app#31]
corectld fails to start after installation. I start it as a user without admin privileges, then I get a privilege escalation prompt, enter password.

```
$ corectld start -d -u rrva -D coreos.local -r 8.8.8.8:53,8.8.4.4:53
[ERROR] Failed to connect to server
Please check your connection settings and ensure that 'corectld' is running.

panic: Failed to connect to server
Please check your connection settings and ensure that 'corectld' is running.


goroutine 1 [running]:
panic(0x4b3f980, 0xc8202aa640)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/TheNewNormal/corectl/vendor/github.com/helm/helm/log.Die(0xc820070f50, 0x69, 0x0, 0x0, 0x0)
	/Users/am/go/src/github.com/TheNewNormal/corectl/vendor/github.com/helm/helm/log/log.go:46 +0xe1
main.main()
	/Users/am/go/src/github.com/TheNewNormal/corectl/cmd/server/main.go:77 +0x7a
[ERROR] Failed to connect to server
Please check your connection settings and ensure that 'corectld' is running.

panic: Failed to connect to server
Please check your connection settings and ensure that 'corectld' is running.


goroutine 1 [running]:
panic(0x4b3f980, 0xc8202aa4b0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/TheNewNormal/corectl/vendor/github.com/helm/helm/log.Die(0xc82006ef50, 0x69, 0x0, 0x0, 0x0)
	/Users/am/go/src/github.com/TheNewNormal/corectl/vendor/github.com/helm/helm/log/log.go:46 +0xe1
main.main()
	/Users/am/go/src/github.com/TheNewNormal/corectl/cmd/server/main.go:77 +0x7a
```
```
corectld version
 Version:	0.7.15
 Go Version:	go1.6.3
 Built:		Wed Aug 03 15:57:49 WEST 2016
 OS/Arch:	darwin/amd64
````

**Comment by AntonioMeireles** [comment]
hi! 
some quick questions ... 
a) `corectld start -d -u rrva` also fails ? 
b) past plz full output of `sudo corectld start -d -u rrva` until it fails 

and thanks in advance for your patience!

**Comment by rrva** [comment]
```sudo /Users/rrj/bin/corectld start  -u rrj -D coreos.local -r 8.8.8.8:53,8.8.4.4:53``` works fine

**Comment by AntonioMeireles** [comment]
hmm. `rrj` or `rrva` ?

**Comment by rrva** [comment]
oops rrj it is :)

**Comment by AntonioMeireles** [comment]
so, no bug, right :-) ? or i missing something ?

**Comment by rrva** [comment]
it did not work when running through GUI directly after installation, but now its not reproducible.. some state got fixed when running corectld through sudo once. the output I pasted was wrong anyway, since I forgot "sudo". Maybe something is not working 100% for users which do not have admin privileges. I can close this, if it reappears for other users then it must have to do with that my user "rrj" has no local admin privileges, I use a separate admin user for that.

**Comment by AntonioMeireles** [comment]
@rrva ok && many thanks!

**Comment by rrva** [comment]
Oh, I think I know what fixed it. I had another DNS server listening on :53 which I do not need and stopped it, forgot that. I think what is missing is that you get the output of corectld start or at least a hint to run `sudo corectld start ...` manually and check the output.

**Comment by valentin-krasontovitsch** [comment]
I think it would be helpful to mention that there should be nothing else hogging port 53, either in the docs / readme, or in the error message that is returned. I had the same problem of the app not starting, which was only fixed after disabling dnsmasq. In my personal opinion, the issue should be reopened.

**Comment by rimusz** [comment]
@valentin-krasontovitsch thanks for the advice, I did update the `corectl.app` readme, and in the mean time we are looking to that DNS issue on `corectl` tool.

**Comment by rimusz** [comment]
here we go https://github.com/TheNewNormal/corectl.app/releases/tag/v0.2.5, notifies if port 53 is in use
