### ISSUE TITLE
0.2.5 DNS No error

### ISSUE THREAD

**Issue by necrogami** [TheNewNormal/corectl.app#33]
I'm running DNSmasq on my macbook and didn't receive the error for DNS in use.

**Comment by rimusz** [comment]
@necrogami can you please run `/usr/sbin/netstat -an | grep LISTEN | grep -w "*.53"` and let me know the output, thanks

**Comment by necrogami** [comment]
________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => sudo brew services stop dnsmasq
Stopping `dnsmasq`... (might take a while)
==> Successfully stopped `dnsmasq` (label: homebrew.mxcl.dnsmasq)

**Started Corectl**
________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => /usr/sbin/netstat -an | grep LISTEN | grep -w "*.53"
tcp46      0      0  *.53                   *.*                    LISTEN     

**Stopped Corectl**
________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => /usr/sbin/netstat -an | grep LISTEN | grep -w "*.53"
________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => sudo brew services start dnsmasq
Password:
==> Successfully started `dnsmasq` (label: homebrew.mxcl.dnsmasq)
________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => /usr/sbin/netstat -an | grep LISTEN | grep -w "*.53"
________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => /usr/sbin/netstat -an | grep LISTEN | grep -w "*.53"
________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => /usr/sbin/netstat -an | grep LISTEN | grep -w "53"
tcp6       0      0  ::1.53                 *.*                    LISTEN     
tcp6       0      0  fe80::1%lo0.53         *.*                    LISTEN     
tcp6       0      0  fe80::f65c:89ff:.53    *.*                    LISTEN     
tcp6       0      0  fe80::74f0:15ff:.53    *.*                    LISTEN     
tcp6       0      0  fe80::be6a:2fff:.53    *.*                    LISTEN     
tcp4       0      0  127.0.0.1.53           *.*                    LISTEN     
tcp4       0      0  128.202.7.201.53       *.*                    LISTEN     
tcp4       0      0  128.202.11.226.53      *.*                    LISTEN

**Comment by rimusz** [comment]
cool, thanks, will change to check for `127.0.0.1.53` instead

**Comment by necrogami** [comment]
since you're already getting sudo might i suggest running something like this: 

________________________________________________________________________________
| ~ @ Antons-MacBook-Pro-2 (necrogami) 
| => sudo lsof -iTCP -sTCP:LISTEN | grep localhost:domain
dnsmasq   94976    nobody    9u  IPv4 0x1fc9a90b81064b99      0t0  TCP localhost:domain (LISTEN)
dnsmasq   94976    nobody   19u  IPv6 0x1fc9a90b7eeda291      0t0  TCP localhost:domain (LISTEN)

**Comment by rimusz** [comment]
nah, `sudo` comes directly from `corectld` directly, this why I'm not using `lsof`

**Comment by rimusz** [comment]
closing, fix in https://github.com/TheNewNormal/corectl.app/releases/tag/v0.2.6
