### ISSUE TITLE
Support disabling startup at login

### ISSUE THREAD

**Issue by lorin** [TheNewNormal/corectl.app#38]
Each time I run corectl.app, it adds itself as a login item so that it automatically starts up the next time I log in. I'd like to be able to disable this behavior.

**Comment by rimusz** [comment]
that is planned at some point of time, need first to implement the `Preferences` where different options can be set. it is time consuming for me.
So I just did a small hack around for now

**Comment by franz-josef-kaiser** [comment]
@rimusz We all suffer from _too less time for side projects_. Can you point to the file and line (best: a blob link) where this feature could be added? And would you consider a multi-stepped plan? If yes: How would that look like? Maybe we can lend a helping hand?

**Comment by rimusz** [comment]
done in https://github.com/TheNewNormal/corectl.app/releases/tag/v0.2.9
