### ISSUE TITLE
Pushing to Docker registry

### ISSUE THREAD

**Issue by srjturner** [TheNewNormal/corectl.app#40]
I am having difficulty pushing images to the Corectl docker registry. 

Firstly, the docs say that the registry run by Corectl will be on 192.168.64.1:5000, but I see it only at localhost - i.e. `curl http://localhost:5000/v2/_catalog` returns `{"repositories":[]}` but `curl http://192.168.64.1:5000/v2/_catalog` just hangs and ping just times out.

Anyway, I'm trying to push to localhost:5000 from my OSX terminal, using Docker beta for OSX:

```
> docker tag 1655bba24bfb localhost:5000/myrepo/hello
> docker push localhost:5000/myrepo/hello
```

I get:

```
The push refers to a repository [localhost:5000/myrepo/hello]
Put http://localhost:5000/v1/repositories/myrepo/hello/: dial tcp [::1]:5000: getsockopt: connection refused
```

I can give the docker debug logs if that helps, but I'm guessing that I am just misunderstanding something fundamental about how Corectl works (or the fault lies with the beta Docker on OSX).

**Comment by rimusz** [comment]
@srjturner it will not work with `docker 4 mac` for some strange reason.
But using kube-solo and coreos-vm (you can use it instaed of docker 4 mac) apps you always use `192.168.64.1:5000` from app's preset shell or from VMs diretcly

**Comment by srjturner** [comment]
OK, thanks, understood.

**Comment by rimusz** [comment]
I'm going to close this one then
