### ISSUE TITLE
App update not working

### ISSUE THREAD

**Issue by franz-josef-kaiser** [TheNewNormal/corectl.app#41]
I just realized that the version installed on my computer is `0.2.8`. Updating told me that everything is up to date, so went to check the GitHub tags. Two things that I noticed: First, there is no tag for 0.2.8 and then that there are much more current versions:

<img width="730" alt="bildschirmfoto 2016-11-21 um 22 40 28" src="https://cloud.githubusercontent.com/assets/387666/20501823/bce73d36-b03b-11e6-9f93-7babe9793911.png">

**Comment by franz-josef-kaiser** [comment]
As mentioned in #42, can we please have a [tag `0.2.9`](https://github.com/TheNewNormal/corectl.app/issues/42#issuecomment-262645325) for the latest merges?

**Comment by rimusz** [comment]
I think you have looked to the wrong repo, `corectl.app` the latest version is v0.2.8.
I will cut release v0.2.9 today
