### ISSUE TITLE
Notification style

### ISSUE THREAD

**Issue by franz-josef-kaiser** [TheNewNormal/corectl.app#42]
Similar to the [Kube Solo OSX](https://github.com/TheNewNormal/kube-solo-osx/issues/155) issue opened previously: The notifications are pretty loud without a reason. Let's change this to a more relaxed version. I will send a PR.

**Comment by rimusz** [comment]
fix merged to master

**Comment by franz-josef-kaiser** [comment]
@rimusz Can you please tag the merge? Currently there's no upgrade available. Thanks in advance! (And have nice holidays!)
