### ISSUE TITLE
Additional network adapter in VMs

### ISSUE THREAD

**Issue by abattye** [TheNewNormal/corectl.app#45]
I have a question rather than an issue, and I'm not sure if this belongs in corectl and kube-cluster-osx. I was wondering if its possible to add an additional network adapter in the VMs spun up to run kube-cluster?

The context is I'm trying to run Openstack on the Kubernetes cluster and for the networking and hypervisor components I need a second, unconfigured adapter on the host.  

Its seems from [this](https://github.com/TheNewNormal/corectl/blob/ad81100b1bf977bfa284084becd9773204667fd8/components/server/run.go#L296-L304) that its possible but I'm not sure where or how I can influence this in the higher level components.

**Comment by AntonioMeireles** [comment]
@abattye, glad you ask... I looked at it in the past but never went to the end for lack of a true use case... will put that on my radar again... and plz open this as a feature request in corectl repo plz... 


Thanks for using us!

**Comment by abattye** [comment]
Thanks for the quick reply - I've added an issue in corectl
