### ISSUE TITLE
Do not tell the user "App can not start" when they cancelled the pass prompt

### ISSUE THREAD

**Issue by franz-josef-kaiser** [TheNewNormal/corectl.app#46]
For me, the _Corectl.App_ is auto starting. This does not mean I need it every day and therefore I quit it after starting if I am on a task without it. It is pretty annoying that I have to click three times just to make it quit – especially when I already cancelled the previous window, indicating that I do not want to enter credentials. I would suggest going even one step further and quitting the app when there was no password provided as this should be indication enough and the app can not do anything meaningful anyway.

**Comment by rimusz** [comment]
done in https://github.com/TheNewNormal/corectl.app/releases/tag/v0.2.9
